POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
get http://localhost:3000/states/
authorization: bearer *tokenID*


###
get http://localhost:3000/states/2
authorization: bearer *tokenID*

###
POST http://localhost:3000/districts/
Authorization: Bearer *tokenID*
Host: localhost
Content-Type: application/json
Content-Length: 114

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
get http://localhost:3000/districts/322
authorization: bearer *tokenID*

###
delete http://localhost:3000/districts/767
authorization: bearer *tokenID*

###
put http://localhost:3000/districts/768
Authorization: Bearer *tokenID*
Host: localhost
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}


###
get http://localhost:3000/states/3/stats/
authorization: bearer *tokenID*
